server:
  port: 7200
  servlet:
    context-path: /dubbo-provider
demo:
  service:
    version: 0.0.1
spring:
  application:
    name: dubbo-provider
  main:
    allow-bean-definition-overriding: true # 不设置会与Spring Boot冲突
  jackson:
    #date timezone
    time-zone: GMT+8
    #date format
    date-format: yyyy-MM-dd
# dubbo 配置
dubbo:
  application:
    id: dubbo-provider-id
    name: dubbo-provider # 服务名
  registry:
    id: registry-id
    address: zookeeper://127.0.0.1:2181 # 注册中心地址
  protocol:
    id: protocol-id
    name: dubbo # 指定通信协议
    port: 20880 # 通信端口，这里指的是与消费者间的通信协议与端口
  provider:
    timeout: 10000 # 配置全局调用服务超时时间，dubbo默认是1s
    retries: 3 # 重试3次
    delay: -1
  scan:
    base-packages: com.dubbo.provider.impl